// Built-in Dispersion (shader) presets tuned for BPM ranges.
// Exported for dynamic import by the Settings UI.
// Each preset only contains Dispersion keys; they will be merged with defaults.

export const SHADER_PRESETS = {
  'DnB • Vortex Drill (160–180)': {
    // Optimized for drum & bass energy
    opacityBase: 0.22,
    opacityTrebleGain: 1.05,
    opacityMin: 0.12,
    opacityMax: 0.92,
    zoomGain: 40,
    zoomBias: -8,
    warpFrom: 'treble',
    warpGain: 1.8,
    warpOnBeat: true,
    warpOnDropBoost: 1.2,
    brightness: 1.0,
    brightnessGain: 0.45,
    contrast: 1.0,
    contrastGain: 0.35,
    twistBase: 0.10,
    twistMax: 1.35,
    twistBassGain: 1.00,
    twistBeatGain: 0.60,
    twistOnsetGain: 0.35,
    twistFluxGain: 0.28,
    twistStutterGain: 0.30,
    twistAttack: 0.26,
    twistRelease: 0.12,
    stutterWindowMs: 100,
    pulseHalfLifeMs: 110,
    flipOnStutter: true,
    flipEveryNBeats: 2,
    travelBase: 0.085,
    travelGain: 0.30,
    travelBeatBoost: 0.10,
    travelDropBoost: 0.20,
    // Variant-specific defaults
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.12,
    steps: 320,
  },
  'BPM 80–100 • Ambient Swirl': {
    // Stronger reactivity while keeping color/tint defaults
    opacityBase: 0.24,
    opacityTrebleGain: 0.60,
    opacityMin: 0.10,
    opacityMax: 0.75,
    zoomGain: 26,
    zoomBias: -12,
    zoomLerp: 0.12,
    warpFrom: 'rms',
    warpGain: 0.9,
    warpOnBeat: true,
    warpOnDropBoost: 0.5,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    // Dynamics
    twistBase: 0.05,
    twistMax: 0.85,
    twistBassGain: 0.40,
    twistBeatGain: 0.22,
    twistOnsetGain: 0.20,
    twistFluxGain: 0.12,
    twistStutterGain: 0.12,
    twistAttack: 0.28,
    twistRelease: 0.22,
    twistFalloff: 1.6,
    stutterWindowMs: 160,
    pulseHalfLifeMs: 180,
    flipOnStutter: true,
    flipEveryNBeats: 0,
    travelBase: 0.05,
    travelGain: 0.12,
    travelBeatBoost: 0.04,
    travelDropBoost: 0.08,
    travelAttack: 0.22,
    travelRelease: 0.12,
    parallaxCentroidGain: 0.06,
    parallaxFluxGain: 0.018,
    parallaxClamp: 0.14,
  },

  'BPM 100–120 • Chill Flow': {
    opacityBase: 0.22,
    opacityTrebleGain: 0.75,
    opacityMin: 0.12,
    opacityMax: 0.80,
    zoomGain: 30,
    zoomBias: -12,
    warpFrom: 'bass',
    warpGain: 1.10,
    warpOnBeat: true,
    warpOnDropBoost: 0.6,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    twistBase: 0.06,
    twistMax: 1.0,
    twistBassGain: 0.55,
    twistBeatGain: 0.30,
    twistOnsetGain: 0.22,
    twistFluxGain: 0.16,
    twistStutterGain: 0.18,
    twistAttack: 0.30,
    twistRelease: 0.18,
    stutterWindowMs: 150,
    pulseHalfLifeMs: 150,
    flipOnStutter: true,
    flipEveryNBeats: 4,
    travelBase: 0.055,
    travelGain: 0.15,
    travelBeatBoost: 0.05,
    travelDropBoost: 0.10,
  },

  'BPM 120–130 • House Groove': {
    opacityBase: 0.20,
    opacityTrebleGain: 0.85,
    opacityMin: 0.12,
    opacityMax: 0.85,
    zoomGain: 34,
    zoomBias: -10,
    warpFrom: 'bass',
    warpGain: 1.30,
    warpOnBeat: true,
    warpOnDropBoost: 0.8,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    twistBase: 0.07,
    twistMax: 1.2,
    twistBassGain: 0.70,
    twistBeatGain: 0.40,
    twistOnsetGain: 0.26,
    twistFluxGain: 0.20,
    twistStutterGain: 0.22,
    twistAttack: 0.30,
    twistRelease: 0.16,
    stutterWindowMs: 130,
    pulseHalfLifeMs: 130,
    flipOnStutter: true,
    flipEveryNBeats: 4,
    travelBase: 0.06,
    travelGain: 0.18,
    travelBeatBoost: 0.06,
    travelDropBoost: 0.12,
  },

  'BPM 130–145 • Techno Drive': {
    opacityBase: 0.18,
    opacityTrebleGain: 0.95,
    opacityMin: 0.12,
    opacityMax: 0.90,
    zoomGain: 38,
    zoomBias: -8,
    warpFrom: 'bass',
    warpGain: 1.60,
    warpOnBeat: true,
    warpOnDropBoost: 1.0,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    twistBase: 0.08,
    twistMax: 1.30,
    twistBassGain: 0.85,
    twistBeatGain: 0.50,
    twistOnsetGain: 0.30,
    twistFluxGain: 0.24,
    twistStutterGain: 0.26,
    twistAttack: 0.28,
    twistRelease: 0.14,
    stutterWindowMs: 120,
    pulseHalfLifeMs: 120,
    flipOnStutter: true,
    flipEveryNBeats: 2,
    travelBase: 0.065,
    travelGain: 0.22,
    travelBeatBoost: 0.07,
    travelDropBoost: 0.12,
  },

  'BPM 160–180 • DnB Warp': {
    opacityBase: 0.18,
    opacityTrebleGain: 1.05,
    opacityMin: 0.14,
    opacityMax: 0.92,
    zoomGain: 42,
    zoomBias: -6,
    warpFrom: 'treble',
    warpGain: 1.80,
    warpOnBeat: true,
    warpOnDropBoost: 1.2,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    twistBase: 0.10,
    twistMax: 1.35,
    twistBassGain: 1.00,
    twistBeatGain: 0.60,
    twistOnsetGain: 0.35,
    twistFluxGain: 0.28,
    twistStutterGain: 0.30,
    twistAttack: 0.26,
    twistRelease: 0.12,
    stutterWindowMs: 100,
    pulseHalfLifeMs: 110,
    flipOnStutter: true,
    flipEveryNBeats: 2,
    travelBase: 0.08,
    travelGain: 0.28,
    travelBeatBoost: 0.08,
    travelDropBoost: 0.16,
  },

  'BPM 180+ • Rave Frenzy': {
    opacityBase: 0.18,
    opacityTrebleGain: 1.10,
    opacityMin: 0.16,
    opacityMax: 0.95,
    zoomGain: 46,
    zoomBias: -4,
    warpFrom: 'treble',
    warpGain: 2.20,
    warpOnBeat: true,
    warpOnDropBoost: 1.35,
    // Color & tone locked to defaults
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.45,
    tintMixMax: 0.85,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.0,
    contrastGain: 0.3,
    twistBase: 0.12,
    twistMax: 1.45,
    twistBassGain: 1.20,
    twistBeatGain: 0.75,
    twistOnsetGain: 0.45,
    twistFluxGain: 0.35,
    twistStutterGain: 0.35,
    twistAttack: 0.24,
    twistRelease: 0.10,
    stutterWindowMs: 90,
    pulseHalfLifeMs: 100,
    flipOnStutter: true,
    flipEveryNBeats: 1,
    travelBase: 0.09,
    travelGain: 0.32,
    travelBeatBoost: 0.10,
    travelDropBoost: 0.20,
  },

  // New Effect Showcase Presets
  'Bass Shock Ribs • Heavy Pulse': {
    // Showcases Bass Shock Ribs effect - pulsing square bands on kicks
    opacityBase: 0.20,
    opacityTrebleGain: 0.70,
    opacityMin: 0.12,
    opacityMax: 0.85,
    zoomGain: 32,
    zoomBias: -10,
    warpFrom: 'bass',
    warpGain: 1.4,
    warpOnBeat: true,
    warpOnDropBoost: 0.9,
    brightness: 1.1,
    brightnessGain: 0.35,
    contrast: 1.15,
    contrastGain: 0.28,
    twistBase: 0.08,
    twistMax: 1.1,
    twistBassGain: 0.75,
    twistBeatGain: 0.45,
    travelBase: 0.07,
    travelGain: 0.20,
    travelBeatBoost: 0.08,
    travelDropBoost: 0.15,
    // NEW: Bass Shock Ribs
    shockRibGain: 1.8,
    shockRibDecay: 0.5,
    shockRibWidth: 0.28,
    drillBox: 1.4,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.10,
    steps: 300,
  },

  'Treble Caustic Veil • Liquid Shimmer': {
    // Showcases Treble Caustic Veil - shimmering liquid layer on treble
    opacityBase: 0.22,
    opacityTrebleGain: 0.90,
    opacityMin: 0.14,
    opacityMax: 0.88,
    zoomGain: 28,
    zoomBias: -12,
    warpFrom: 'treble',
    warpGain: 1.2,
    warpOnBeat: false,
    warpOnDropBoost: 0.4,
    tintHue: 0.15,
    tintSat: 0.25,
    tintMixBase: 0.12,
    tintMixChromaGain: 0.55,
    tintMixMax: 0.80,
    brightness: 1.05,
    brightnessGain: 0.38,
    contrast: 1.08,
    contrastGain: 0.25,
    twistBase: 0.06,
    twistMax: 0.95,
    twistBassGain: 0.50,
    twistBeatGain: 0.28,
    travelBase: 0.06,
    travelGain: 0.16,
    // NEW: Treble Caustic Veil
    causticMix: 1.4,
    causticScale: 1.8,
    causticHueShift: 0.5,
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.10,
    steps: 300,
  },

  'Fractal Bloom • Downbeat Explosion': {
    // Showcases Fractal Bloom - radial bloom on downbeats
    opacityBase: 0.20,
    opacityTrebleGain: 0.85,
    opacityMin: 0.12,
    opacityMax: 0.90,
    zoomGain: 36,
    zoomBias: -8,
    warpFrom: 'bass',
    warpGain: 1.6,
    warpOnBeat: true,
    warpOnDropBoost: 1.0,
    brightness: 1.15,
    brightnessGain: 0.42,
    contrast: 1.2,
    contrastGain: 0.32,
    twistBase: 0.09,
    twistMax: 1.25,
    twistBassGain: 0.90,
    twistBeatGain: 0.55,
    travelBase: 0.075,
    travelGain: 0.24,
    travelBeatBoost: 0.09,
    travelDropBoost: 0.18,
    // NEW: Fractal Bloom
    fractalBloomGain: 2.2,
    fractalBloomDecay: 0.55,
    fractalBloomRadius: 0.5,
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.12,
    steps: 320,
  },

  'Flux Ripple Bands • Flowing Motion': {
    // Showcases Flux Ripple Bands - horizontal ripples driven by flux
    opacityBase: 0.21,
    opacityTrebleGain: 0.80,
    opacityMin: 0.13,
    opacityMax: 0.82,
    zoomGain: 30,
    zoomBias: -11,
    warpFrom: 'rms',
    warpGain: 1.1,
    warpOnBeat: true,
    warpOnDropBoost: 0.6,
    brightness: 1.0,
    brightnessGain: 0.4,
    contrast: 1.1,
    contrastGain: 0.28,
    twistBase: 0.07,
    twistMax: 1.05,
    twistBassGain: 0.60,
    twistFluxGain: 0.25,
    travelBase: 0.065,
    travelGain: 0.18,
    travelBeatBoost: 0.06,
    travelDropBoost: 0.12,
    // NEW: Flux Ripple Bands
    rippleGain: 2.0,
    rippleSpeed: 1.8,
    rippleDensity: 4.5,
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.10,
    steps: 300,
  },

  'Chroma Prism Breathing • Color Spectrum': {
    // Showcases Chroma Prism Breathing - color-reactive prism slices
    opacityBase: 0.22,
    opacityTrebleGain: 0.75,
    opacityMin: 0.12,
    opacityMax: 0.85,
    zoomGain: 28,
    zoomBias: -10,
    warpFrom: 'rms',
    warpGain: 1.0,
    warpOnBeat: true,
    warpOnDropBoost: 0.5,
    tintHue: 0.0,
    tintSat: 0.0,
    tintMixBase: 0.0,
    tintMixChromaGain: 0.50,
    tintMixMax: 0.85,
    brightness: 1.1,
    brightnessGain: 0.40,
    contrast: 1.15,
    contrastGain: 0.30,
    twistBase: 0.06,
    twistMax: 1.0,
    twistBassGain: 0.55,
    travelBase: 0.06,
    travelGain: 0.16,
    // NEW: Chroma Prism Breathing
    prismIntensity: 1.8,
    prismSlices: 6,
    prismBreath: 0.6,
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.10,
    steps: 300,
  },

  'Psy Vortex Ultimate • All Effects': {
    // Ultimate preset combining ALL new effects for maximum visual impact
    opacityBase: 0.20,
    opacityTrebleGain: 1.0,
    opacityMin: 0.14,
    opacityMax: 0.92,
    zoomGain: 38,
    zoomBias: -8,
    warpFrom: 'treble',
    warpGain: 1.8,
    warpOnBeat: true,
    warpOnDropBoost: 1.1,
    tintHue: 0.85,
    tintSat: 0.7,
    tintMixBase: 0.30,
    tintMixChromaGain: 0.90,
    tintMixMax: 0.95,
    brightness: 1.2,
    brightnessGain: 0.48,
    contrast: 1.25,
    contrastGain: 0.38,
    twistBase: 0.10,
    twistMax: 1.35,
    twistBassGain: 0.95,
    twistBeatGain: 0.60,
    twistOnsetGain: 0.35,
    twistFluxGain: 0.30,
    twistStutterGain: 0.32,
    twistAttack: 0.26,
    twistRelease: 0.12,
    stutterWindowMs: 110,
    pulseHalfLifeMs: 120,
    flipOnStutter: true,
    flipEveryNBeats: 2,
    travelBase: 0.08,
    travelGain: 0.26,
    travelBeatBoost: 0.09,
    travelDropBoost: 0.17,
    // ALL NEW EFFECTS COMBINED
    shockRibGain: 1.5,
    shockRibDecay: 0.55,
    shockRibWidth: 0.32,
    causticMix: 1.2,
    causticScale: 1.6,
    causticHueShift: 0.8,
    fractalBloomGain: 1.8,
    fractalBloomDecay: 0.6,
    fractalBloomRadius: 0.45,
    rippleGain: 1.6,
    rippleSpeed: 1.5,
    rippleDensity: 4.0,
    prismIntensity: 1.5,
    prismSlices: 5,
    prismBreath: 0.5,
    drillBox: 1.5,
    drillRadius: 1.0,
    repPeriod: 4.0,
    rotDepth: 0.12,
    steps: 320,
  },
};

// Determine which preset name to use for a given BPM.
export function pickShaderPresetForBpm(bpm) {
  const n = Number(bpm) || 0;
  let name = null;
  if (n > 180) name = 'BPM 180+ • Rave Frenzy';
  else if (n >= 160) name = 'BPM 160–180 • DnB Warp';
  else if (n >= 130) name = 'BPM 130–145 • Techno Drive';
  else if (n >= 120) name = 'BPM 120–130 • House Groove';
  else if (n >= 100) name = 'BPM 100–120 • Chill Flow';
  else name = 'BPM 80–100 • Ambient Swirl';
  return { name, values: SHADER_PRESETS[name] };
}



